### ISSUE TITLE
Installation error on Debian 8

### ISSUE THREAD

**Issue by montaniasystemab** [runfalk/certbot-glesys#1]
Hi! Thanks for providing this plugin, just what I was looking for.

However I'm getting this error message when trying to install the plugin on Debian 8 Jessie:

```
Downloading/unpacking cryptography>=0.8 (from acme>=0.17.0->certbot-glesys)
  Downloading cryptography-2.1.4.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/tmp/pip-build-KeVYwy/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'
```

I'm not familiar enough with python to understand how to proceed. I've got both python 2 and python 3 installed on this machine: 

```
# python --version
Python 2.7.9
# python3 --version
Python 3.4.2
```

Certbot is also installed and working fine: 
```
# /opt/certbot/certbot-auto --version
certbot 0.21.1
```

Any suggestions how to get the plugin installed?

**Comment by runfalk** [comment]
Looks like you have problems  with a sub-dependency. This is probably due to an ancient version of `setuptools`.

Try this:

```bash
sudo pip install setuptools pip
sudo pip install certbot-glesys
```

**Comment by montaniasystemab** [comment]
Thank you for responding so quickly!

I was able to get it installed now by upgrading pip and setuptools and installing libxml2-dev and libxslt-dev 

However it doesn't seem like certbot is recognizing the plugin: 

```
# /opt/certbot/certbot-auto certonly --manual --preferred-challenges=dns --certbot-glesys:auth-credentials /etc/letsencrypt/glesys.ini -d subdomain.domain.tld
usage:
  certbot-auto [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --certbot-glesys:auth-credentials /etc/letsencrypt/glesys.ini
```

This is the full output of the installation
https://gist.github.com/montaniasystemab/0cc3f5f85b96c86437027958932e3406

**Comment by runfalk** [comment]
Your command must specify that you want to make use of the `certbot-glesys` authenticator:

```
/opt/certbot/certbot-auto certonly --text --authenticator certbot-glesys:auth --certbot-glesys:auth-credentials /etc/letsencrypt/glesys.ini --certbot-glesys:auth-propagation-seconds 90 -d subdomain.domain.tld
```

I've found to have greater success rate when using `--certbot-glesys:auth-propagation-seconds 90`.

If this doesn't work you probably want to install certbot using pip as well. There might be an issue where the certbot in `/opt` doesn't read from the same directory as pip installs to.

```bash
sudo pip install certbot
```

**Comment by montaniasystemab** [comment]
Correct, the installation in `/opt` did not pick up the plugin and my certbot installation using pip seemed thoroughly broken. 

After these steps I was able to get certbot running: 

```
# pip install --upgrade pip enum34
# pip install setuptools==5.1
# easy_install -U cffi
# pip install py2-ipaddress
```

After resolving these issues I got this error message from certbot:

```
InvalidSchema: No connection adapters were found for ' https://api.glesys.com//domain/listrecords/'
```

Removing the trailing space from this URL resolved that error:
https://github.com/runfalk/certbot-glesys/blob/master/certbot_glesys.py#L34

> Congratulations!

And now I've got my certificate.

Thank you for your help with these issues. This was still easier than trying to implement this on my own =)

**Comment by runfalk** [comment]
Good to hear it worked out for you!
