### ISSUE TITLE
pip3 package crash

### ISSUE THREAD

**Issue by Lillecarl** [runfalk/certbot-glesys#3]
I don't know if you're maintaining the pip3 package, however when i tested it out i got this error:

https://gist.github.com/Lillecarl/0675730265e9e304b3fc76f9ad7ca812

So what i did was i removed the leading space and the trailing / in the base URL variable, which resolved the issue and gave me a certificate.

The command i used was certbot certonly --server https://acme-v02.api.letsencrypt.org/directory -d *.dicloud.se -d dicloud.se in case that's of interest (using new wildcard compatible API 👍 )

I didn't try installing it from your repo, i know very little about both the python environment and language so this is all i can do 😄

**Comment by runfalk** [comment]
This was fixed with PR #2, but I forgot to release a new version on PyPI.

I've released version 0.1.1 (https://pypi.python.org/pypi/certbot-glesys/0.1.1). You should be able to:

```bash
pip3 install --upgrade certbot-glesys
```

and it should update.

Let me know if this fixes your issue.

**Comment by Lillecarl** [comment]
Now it's working, and yeah it's supernice! 👍 Thanks!
