### ISSUE TITLE
SWAG integration

### ISSUE THREAD

**Issue by peglah** [runfalk/certbot-glesys#9]
Hi!

Can this certbot plugin be integrated into [SWAG](https://github.com/linuxserver/docker-swag) or might there be computability problems?

**Comment by runfalk** [comment]
Hi there!

I don't think there would be any compatibility issues, you would simply need to add it to the `pip install` call in the `Dockerfile`. A quick look at the `README` for the project suggests that you can then configure the container to use the GleSyS plugin using environment variables.

The only thing I could see that would make this a problem is if newer certbot versions has broken the plugin. I think latest I've tested with it `2.6.0` and the current is `2.7.4`.

**Comment by peglah** [comment]
Thanks for your reply.

I've cloned the swag repo and tested it locally. Works without problems as far as I can see.

I'll fork swag and make a PR as soon as possible. Thanks again.

Ha de gött :)

**Comment by peglah** [comment]
[Add GleSYS DNS plugin #425](https://github.com/linuxserver/docker-swag/pull/425) :)
